BOWTIE2	/opt/miniconda3/envs/bio-qc/bin/bowtie2
THREADS	4
DATABASE	Ecoli	/mnt/d/1.WorkDir/RedBook/content/素材/read-qc/043-contamination-screening/db/bt2/ecoli
DATABASE	PhiX	/mnt/d/1.WorkDir/RedBook/content/素材/read-qc/043-contamination-screening/db/bt2/phix
DATABASE	Lambda	/mnt/d/1.WorkDir/RedBook/content/素材/read-qc/043-contamination-screening/db/bt2/lambda
